services:
  mongo_db:
    image: mongo:5.0.2
    container_name: mongo_db
    hostname: mongo_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
    ports:
      - $MONGO_HOST_PORT:$MONGO_DOCKER_PORT
    volumes:
      - db:/data/db

  storage-app:
    depends_on:
      - mongo_db
    container_name: storage_app
    hostname: storage_app
    build: ./storage-app
    env_file: ./.env
    ports:
      - $SERVICE_HOST_PORT:$SERVICE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGO_USER:$MONGO_PASSWORD@mongo_db:$MONGO_DOCKER_PORT/$MONGO_DATABASE?authSource=admin"
        }'
    volumes:
      - files:/storage-app/files

volumes:
  db:
  files: