server:
  port: 8080
  servlet:
    context-path: /api/v1/storage-app

spring:
  application:
    name: storage-app
  data:
    mongodb:
      uri: mongodb://root:storage_app@localhost:27017/storage_app_db?authSource=admin
